"""Constrained executor for the Pandas programs generated by DPC."""

from __future__ import annotations

import ast
import multiprocessing
import traceback
from typing import Any

import pandas as pd


_ALLOWED_BUILTINS = {
    "abs": abs,
    "all": all,
    "any": any,
    "bool": bool,
    "dict": dict,
    "enumerate": enumerate,
    "float": float,
    "int": int,
    "len": len,
    "list": list,
    "max": max,
    "min": min,
    "range": range,
    "round": round,
    "set": set,
    "sorted": sorted,
    "str": str,
    "sum": sum,
    "tuple": tuple,
    "zip": zip,
}

_BLOCKED_NODES = (
    ast.AsyncFunctionDef,
    ast.ClassDef,
    ast.Delete,
    ast.Global,
    ast.ImportFrom,
    ast.Nonlocal,
    ast.Try,
    ast.While,
    ast.With,
)

_BLOCKED_CALLS = {
    "__import__",
    "breakpoint",
    "compile",
    "eval",
    "exec",
    "exit",
    "getattr",
    "globals",
    "help",
    "input",
    "locals",
    "open",
    "quit",
    "setattr",
    "vars",
}

_BLOCKED_ATTRIBUTES = {
    "eval",
    "exec",
    "popen",
    "system",
    "urlopen",
    "read_csv",
    "read_excel",
    "read_feather",
    "read_fwf",
    "read_hdf",
    "read_html",
    "read_json",
    "read_orc",
    "read_parquet",
    "read_pickle",
    "read_sas",
    "read_spss",
    "read_sql",
    "read_sql_query",
    "read_sql_table",
    "read_stata",
    "to_clipboard",
    "to_csv",
    "to_excel",
    "to_feather",
    "to_hdf",
    "to_html",
    "to_json",
    "to_latex",
    "to_markdown",
    "to_orc",
    "to_parquet",
    "to_pickle",
    "to_sql",
    "to_stata",
}

_ALLOWED_PD_ROOTS = {
    "Categorical",
    "DataFrame",
    "Grouper",
    "Index",
    "NamedAgg",
    "Series",
    "Timestamp",
    "concat",
    "crosstab",
    "cut",
    "date_range",
    "isna",
    "merge",
    "notna",
    "pivot_table",
    "qcut",
    "to_datetime",
    "to_numeric",
}


def _attribute_chain(node: ast.AST) -> list[str] | None:
    parts: list[str] = []
    current = node
    while isinstance(current, ast.Attribute):
        parts.append(current.attr)
        current = current.value
    if not isinstance(current, ast.Name):
        return None
    parts.append(current.id)
    return list(reversed(parts))


class _SafetyVisitor(ast.NodeVisitor):
    def __init__(self, defined_functions: set[str]) -> None:
        self.defined_functions = defined_functions

    def generic_visit(self, node: ast.AST) -> None:
        if isinstance(node, _BLOCKED_NODES):
            raise ValueError(f"{type(node).__name__} is not allowed")
        super().generic_visit(node)

    def visit_Import(self, node: ast.Import) -> None:
        for alias in node.names:
            if alias.name != "pandas":
                raise ValueError(
                    f"importing module {alias.name!r} is not allowed"
                )
            if alias.asname not in {None, "pd"}:
                raise ValueError("pandas may only be imported as pd")

    def visit_FunctionDef(self, node: ast.FunctionDef) -> None:
        if node.name.startswith("_"):
            raise ValueError("private helper function names are not allowed")
        if node.decorator_list:
            raise ValueError("function decorators are not allowed")
        self.generic_visit(node)

    def visit_Name(self, node: ast.Name) -> None:
        if node.id.startswith("__") or node.id in _BLOCKED_CALLS:
            raise ValueError(f"name {node.id!r} is not allowed")

    def visit_Attribute(self, node: ast.Attribute) -> None:
        if node.attr.startswith("_") or node.attr in _BLOCKED_ATTRIBUTES:
            raise ValueError(f"attribute {node.attr!r} is not allowed")
        chain = _attribute_chain(node)
        if chain and chain[0] == "pd":
            if len(chain) < 2 or chain[1] not in _ALLOWED_PD_ROOTS:
                raise ValueError(
                    f"pandas attribute {'.'.join(chain)!r} is not allowed"
                )
        self.generic_visit(node)

    def visit_Call(self, node: ast.Call) -> None:
        if isinstance(node.func, ast.Name):
            name = node.func.id
            if name in _BLOCKED_CALLS:
                raise ValueError(f"call {name!r} is not allowed")
            if (
                name not in _ALLOWED_BUILTINS
                and name not in self.defined_functions
            ):
                raise ValueError(f"calling global {name!r} is not allowed")
        self.generic_visit(node)


def _validate(code: str) -> None:
    tree = ast.parse(code, mode="exec")
    defined_functions = {
        node.name
        for node in tree.body
        if isinstance(node, ast.FunctionDef)
    }
    _SafetyVisitor(defined_functions).visit(tree)


def _safe_import(
    name: str,
    globals=None,
    locals=None,
    fromlist=(),
    level: int = 0,
):
    del globals, locals, fromlist, level
    if name == "pandas":
        return pd
    raise ImportError(f"importing module {name!r} is not allowed")


def _worker(test_data: dict, code: str, connection) -> None:
    try:
        namespace: dict[str, Any] = {
            "__builtins__": {
                **_ALLOWED_BUILTINS,
                "__import__": _safe_import,
            },
            "pd": pd,
        }
        for table_name, rows in test_data.items():
            variable = table_name.replace(" ", "_")
            if not variable.isidentifier() or variable.startswith("_"):
                raise ValueError(f"unsafe DataFrame variable name: {variable!r}")
            namespace[variable] = pd.DataFrame(rows)
        exec(code, namespace, namespace)
        result = namespace.get("result")
        if not isinstance(result, pd.DataFrame):
            if isinstance(result, (list, dict)):
                result = pd.DataFrame(result)
            elif isinstance(result, (int, float, str)):
                result = pd.DataFrame([result])
            else:
                raise ValueError("code must define result as a DataFrame")
        connection.send(("ok", result))
    except BaseException:
        connection.send(("error", traceback.format_exc()))
    finally:
        connection.close()


class SafePythonExecutor:
    """DPC-compatible executor with validation, isolation, and a timeout."""

    @staticmethod
    def execute(test_data: dict, code: str, timeout: int = 30) -> Any:
        clean_code = code.strip()
        if clean_code.startswith("```python"):
            clean_code = clean_code[9:]
        if clean_code.endswith("```"):
            clean_code = clean_code[:-3]
        clean_code = clean_code.strip()
        try:
            _validate(clean_code)
        except (SyntaxError, ValueError) as exc:
            return f"Error: Unsafe generated Python: {exc}"

        context = multiprocessing.get_context("spawn")
        parent, child = context.Pipe(duplex=False)
        process = context.Process(
            target=_worker,
            args=(test_data, clean_code, child),
        )
        process.start()
        child.close()
        try:
            if parent.poll(timeout):
                status, result = parent.recv()
                process.join(timeout=1)
                return result
            process.terminate()
            process.join(timeout=1)
            if process.is_alive():
                process.kill()
                process.join(timeout=1)
            return f"Error: Python execution timed out after {timeout} seconds."
        finally:
            parent.close()
